enableGlobalCache: false

# Using pnpm until https://github.com/microsoft/typescript-go/pull/1966 is merged/decided
# Can move back to pnp after
nodeLinker: pnpm

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.15.4
  "@stepwisehq/prosemirror-collab-commit@*":
    peerDependencies:
      "prosemirror-model": "^1.0.0"
      "prosemirror-transform": "^1.0.0"
  "@parcel/runtime-rsc@*":
    peerDependencies:
      "react": "^19.1.0"
