approvedGitRepositories:
  - "**"

enableGlobalCache: false

enableScripts: true

nodeLinker: pnpm

npmMinimalAgeGate: 0

packageExtensions:
  "@fumadocs/tailwind@*":
    dependencies:
      tailwindcss: 4.2.4
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.15.4
  "@parcel/runtime-rsc@*":
    peerDependencies:
      react: ^19.1.0
  "@stepwisehq/prosemirror-collab-commit@*":
    peerDependencies:
      prosemirror-model: ^1.0.0
      prosemirror-transform: ^1.0.0
  "@tanstack/start-plugin-core@*":
    dependencies:
      vite: 8.0.10
  tsconfck@*:
    dependencies:
      typescript: ^6.0.0
  typedoc-plugin-frontmatter@*:
    peerDependencies:
      typedoc: ^0.28.0
  typedoc@*:
    peerDependencies:
      typedoc-plugin-frontmatter: ^1.0.0
      typedoc-plugin-markdown: ^4.0.0
