enableGlobalCache: false

packageExtensions:
  "@parcel/node-resolver-core@*":
    dependencies:
      "@parcel/core": 2.15.4
  "@handlewithcare/react-prosemirror@*":
    peerDependencies:
      "react-reconciler": "*"
  "@stepwisehq/prosemirror-collab-commit@*":
    peerDependencies:
      "prosemirror-model": "^1.0.0"
      "prosemirror-transform": "^1.0.0"
  "@parcel/runtime-rsc@*":
    peerDependencies:
      "react": "^19.1.0"
