[[language]]
name = "typescript"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "tsx"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "javascript"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "jsx"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "json"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[[language]]
name = "markdown"
formatter = { command = "yarn", args = ["oxfmt", "--stdin-filepath", "%{buffer_name}"] }

[language-server.typescript-language-server.config]
hostInfo = "helix"
vtsls.autoUseWorkspaceTsdk = true
typescript.updateImportsOnFileMove.enabled = "always"
typescript.preferences.importModuleSpecifier = "non-relative"
typescript.preferences.importModuleSpecifierEnding = "auto"
typescript.tsdk = "./.yarn/sdks/typescript/lib"
