[language-server.oxfmt]
command = "yarn"
args = ["oxfmt", "--lsp"]
provideFormatter = true

[language-server.oxlint]
command = "yarn"
args = ["oxlint", "--lsp"]

[[language]]
name = "typescript"
language-servers = ["oxfmt", "oxlint"]

[[language]]
name = "tsx"
language-servers = ["oxfmt", "oxlint"]

[[language]]
name = "javascript"
language-servers = ["oxfmt", "oxlint"]

[[language]]
name = "jsx"
language-servers = ["oxfmt", "oxlint"]

[[language]]
name = "json"
language-servers = ["oxfmt", "oxlint"]

[[language]]
name = "markdown"
language-servers = ["oxfmt", "oxlint"]

