name: check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run check:format

      - name: Types
        run: pnpm run check:types

      - name: Lint
        run: pnpm run check:lint

      - name: Versions
        run: node scripts/checkVersions.mts

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm --filter @pitter-patter/shuffle exec playwright install --with-deps chromium

      - name: Test
        run: pnpm test

  bump-version:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for version bump
        run: node scripts/bumpVersions.mts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
